services:
  m-fastgate:
    image: m-fastgate:latest
    container_name: m-fastgate
    restart: unless-stopped
    ports:
      - "8514:8514"
    volumes:
      # 数据库持久化 (宿主机:容器) - 使用bind mount
      - type: bind
        source: ./data
        target: /app/data
      # 日志持久化 (宿主机:容器) - 使用bind mount
      - type: bind
        source: ./logs
        target: /app/logs
      # 配置文件挂载 (宿主机:容器) - 使用bind mount
      - type: bind
        source: ./config
        target: /app/config
        read_only: true
    environment:
      - ENVIRONMENT=production
      - PYTHONUNBUFFERED=1
    networks:
      - fastgate-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8514/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  fastgate-network:
    driver: bridge

volumes:
  fastgate-data:
    driver: local 